# Usa la imagen oficial de MariaDB
FROM mariadb:10.6

# Copiar scripts de inicialización
# MariaDB ejecuta automáticamente cualquier script .sql, .sh o .gz en este directorio
# Esto es útil para crear tablas y poblar datos iniciales.
COPY Data/ /docker-entrypoint-initdb.d/
